# Generated by Django 2.0 on 2024-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240220_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroeletiva',
            name='vagas_disponiveis',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
