# Generated by Django 2.0 on 2024-02-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cadastroeletiva_vagas_disponiveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroeletiva',
            name='vagas_disponiveis',
        ),
    ]
