# Generated by Django 2.1.5 on 2024-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_cadastroeletiva_vagas_disponiveis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroAluno',
        ),
        migrations.DeleteModel(
            name='CadastroEletiva',
        ),
        migrations.DeleteModel(
            name='EletivaAluno',
        ),
    ]
