# Generated by Django 2.1.5 on 2024-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_auto_20240223_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroEletiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProf', models.CharField(max_length=100)),
                ('nomeEletiva', models.CharField(max_length=100)),
                ('anoSerie', models.CharField(max_length=30)),
                ('qntVagas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EletivaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30)),
                ('eletiva', models.CharField(max_length=50)),
            ],
        ),
    ]
