# Generated by Django 2.1.5 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cadastroaluno_cadastroeletiva_eletivaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroeletiva',
            name='bloco',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
