# Generated by Django 2.1.5 on 2024-02-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cadastroeletiva_bloco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(upload_to='')),
            ],
        ),
    ]
