# Generated by Django 2.1.5 on 2024-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_arq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EletivaAluno',
        ),
        migrations.AddField(
            model_name='cadastroaluno',
            name='eletiva_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastroaluno',
            name='eletiva_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastroaluno',
            name='turma',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
