# Generated by Django 2.1.5 on 2024-03-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20240315_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroaluno',
            old_name='eletiva_1',
            new_name='eletiva1',
        ),
        migrations.RenameField(
            model_name='cadastroaluno',
            old_name='eletiva_2',
            new_name='eletiva2',
        ),
    ]
